version: '3.3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - 15672:15672
            - 5672:5672
    mongo:
        image: mongo:latest
        container_name: 'mongo'
        ports:
            - 27017:27017
volumes:
  static-content:
  db-content:
